// Generated by CoffeeScript 1.4.0
(function() {
  var Submachine, exports,
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Submachine = (function() {
    var clone, isArray;

    isArray = Array.isArray || function(maybe_array) {
      return {}.toString.apply(maybe_array) === "[object Array]";
    };

    clone = function(obj) {
      var c, key;
      if (!((obj != null) && typeof obj === "object")) {
        return obj;
      }
      c = new obj.constructor();
      for (key in obj) {
        c[key] = clone(obj[key]);
      }
      return c;
    };

    Submachine.hasStates = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (isArray(args[0])) {
        return this.prototype.states = args[0];
      } else {
        return this.prototype.states = args;
      }
    };

    Submachine.transition = function(obj) {
      var _base, _base1, _base2, _name, _name1, _ref, _ref1, _ref2;
      if (!((obj != null) && (obj.from != null) && (obj.to != null) && (obj.on != null))) {
        throw new Error("transition must define 'from', 'to' and 'on'");
      }
      if ((_ref = (_base = this.prototype).events) == null) {
        _base.events = {};
      }
      if (!this.prototype.hasOwnProperty("events")) {
        this.prototype.events = clone(this.prototype.events);
      }
      if ((_ref1 = (_base1 = this.prototype.events)[_name = obj.on]) == null) {
        _base1[_name] = [];
      }
      this.prototype.events[obj.on].push({
        from: obj.from,
        to: obj.to
      });
      return (_ref2 = (_base2 = this.prototype)[_name1 = obj.on]) != null ? _ref2 : _base2[_name1] = function() {
        var args, tr, _i, _len, _ref3, _results;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        _ref3 = this.events[obj.on];
        _results = [];
        for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
          tr = _ref3[_i];
          if (this.state === tr.from || tr.from === "*") {
            this.switchTo.apply(this, [tr.to].concat(__slice.call(args)));
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
    };

    Submachine._addStateCallback = function(state, type, cbk) {
      var _base, _base1, _ref, _ref1;
      if ((_ref = (_base = this.prototype).callbacks) == null) {
        _base.callbacks = {};
      }
      if (!this.prototype.hasOwnProperty("callbacks")) {
        this.prototype.callbacks = clone(this.prototype.callbacks);
      }
      if ((_ref1 = (_base1 = this.prototype.callbacks)[state]) == null) {
        _base1[state] = {};
      }
      return this.prototype.callbacks[state][type] = cbk;
    };

    Submachine.onEnter = function(state, cbk) {
      return this._addStateCallback(state, "onEnter", cbk);
    };

    Submachine.onLeave = function(state, cbk) {
      return this._addStateCallback(state, "onLeave", cbk);
    };

    Submachine.setupState = function(state, cbks) {
      if (cbks == null) {
        cbks = {};
      }
      if (cbks.onEnter != null) {
        this.onEnter(state, cbks.onEnter);
      }
      if (cbks.onLeave != null) {
        return this.onLeave(state, cbks.onLeave);
      }
    };

    Submachine.subclass = function(fn) {
      var parent, prop, sub, value;
      parent = this;
      sub = function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (this.init != null) {
          return this.init.apply(this, args);
        } else {
          return parent.apply(this, args);
        }
      };
      for (prop in parent) {
        value = parent[prop];
        sub[prop] = value;
      }
      sub.prototype = new parent;
      sub.prototype.constructor = sub;
      if (fn != null) {
        fn.call(sub, sub.prototype);
      }
      return sub;
    };

    function Submachine(state) {
      if (state != null) {
        this.initState(state);
      }
    }

    Submachine.prototype.initState = function(state) {
      if (this.state != null) {
        throw new Error("state was already initialized");
      }
      return this.switchTo(state);
    };

    Submachine.prototype.switchTo = function() {
      var args, state, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8;
      state = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (__indexOf.call(this.states, state) < 0) {
        throw new Error("invalid state " + state);
      }
      if ((_ref = this.callbacks) == null) {
        this.callbacks = {};
      }
      if (this.state != null) {
        if ((_ref1 = this.callbacks[this.state]) != null) {
          if ((_ref2 = _ref1.onLeave) != null) {
            _ref2.apply(this, args);
          }
        }
        if ((_ref3 = this.callbacks["*"]) != null) {
          if ((_ref4 = _ref3.onLeave) != null) {
            _ref4.apply(this, args);
          }
        }
      }
      this.state = state;
      if ((_ref5 = this.callbacks[this.state]) != null) {
        if ((_ref6 = _ref5.onEnter) != null) {
          _ref6.apply(this, args);
        }
      }
      return (_ref7 = this.callbacks["*"]) != null ? (_ref8 = _ref7.onEnter) != null ? _ref8.apply(this, args) : void 0 : void 0;
    };

    return Submachine;

  })();

  if (typeof exports !== "undefined" && exports !== null) {
    if ((typeof module !== "undefined" && module !== null) && (module.exports != null)) {
      exports = module.exports = Submachine;
    }
    exports.Submachine = Submachine;
  } else if (typeof define === "function" && define.amd) {
    define(function() {
      return Submachine;
    });
  } else {
    this.Submachine = Submachine;
  }

}).call(this);
